config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Read all tasks (index)
  get '/tasks', to: 'tasks#index'
  # Add a page where user can create a new task (form)
  get '/tasks/new', to: 'tasks#new'
  # Save the task instance created by the user in the form
  post '/tasks', to: 'tasks#create'
  # Read a specific tasks (show)
  get '/tasks/:id', to: 'tasks#show', as: :task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>Tasks:</h1>


<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.title, task_path(task) %></li>
  <% end %>
</ul>

<%= link_to "Add new task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= form_for(@task) do |form| %>
  <%= form.label :title, "Title" %>
  <%= form.text_field :title %>
  <%= form.label :details, "Details" %>
  <%= form.text_field :details %>
  <%= form.submit %>
<% end %>

<%= link_to "Back to list", tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<%= @task.details %>

<%= link_to "Back to list", tasks_path %>